[project]
name = "week-5"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "evidently>=0.7.8",
    "ipykernel>=6.29.5",
    "pandas>=2.3.0",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]
